# syntax=docker/dockerfile:1
# check=error=true

# This Dockerfile is designed for development. See Dockerfile for production build.

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.2.10
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# Rails app lives here
WORKDIR /rails

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3 default-libmysqlclient-dev chromium xz-utils build-essential && \
    ARCH=$(case $(uname -m) in aarch64) echo "arm64" ;; x86_64) echo "x64" ;; esac) && \
    curl -fsSL https://nodejs.org/dist/v24.18.1/node-v24.18.1-linux-${ARCH}.tar.xz | tar -xJ -C /usr/local --strip-components=1 && \
    ln -s /usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2 /usr/local/lib/libjemalloc.so && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set development environment variables and enable jemalloc for reduced memory usage and latency.
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle" \
    LD_PRELOAD="/usr/local/lib/libjemalloc.so"

COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]